services:
  redis:
    image: redis:8.0.2-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - subliprint_network
  mongodb:
    image: mongo:8.0.10-noble
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: jasanz
      MONGO_INITDB_ROOT_PASSWORD: J4s4nz
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'
    networks:
      - subliprint_network

  backend:
    image: subli_print:latest
    container_name: subli_print
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
      args:
        - 'PORT=${PORT}'
    ports:
      - '${PORT}:${PORT}'
    environment:
      - NODE_ENV=production
    networks:
      - subliprint_network

  backend-dev:
    image: subli_print_dev:latest
    container_name: subli_print_dev
    restart: unless-stopped
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    command: npm run start:dev
    develop:
      watch:
        - action: sync
          path: .
          target: /src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb
    networks:
      - subliprint_network
volumes:
  mongo_data:
  redis_data:

networks:
  subliprint_network:
    driver: bridge
